"""
Django settings for CentralAPIServicesMgmtProject project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fi)_rwu!*(ie!^68d*4#q&2tej^8*&0!7=lyq_nihcu9#**6&5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0', '192.168.62.69', '192.168.100.61', '116.68.205.72', 'mis.digital', '192.168.101.188']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    #'django.contrib.staticfiles',
	'django_user_agents',
    'rest_framework',
    'django_filters',
    'PharmaCampaignApp',
	'ConstructionEquipmentApp',
	'YamahaRegistrationAPI',
	'RxCampS3Uploader',
    'GenericServiceRESTApp',
	'YamahaBookingApp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'CentralAPIServicesMgmtProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CentralAPIServicesMgmtProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'PharmaCampaign': {
        'NAME': 'Campaign',
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '192.168.100.75',
        'USER': 'sa',
        'PASSWORD': 'dataport',
        'OPTIONS': {
            'driver' : 'SQL Server Native Client 11.0',
            'driver_supports_utf8' : 'True',
            'use_legacy_date_fields': 'True'
        }
    },
	'MotorConstructionEquipment': {
        'NAME': 'MotorConstructionEquip',
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '192.168.100.61',
        'USER': 'sa',
        'PASSWORD': 'dataport',
        'OPTIONS': {
            'driver' : 'SQL Server Native Client 11.0',
            'driver_supports_utf8' : 'True',
            'use_legacy_date_fields': 'True'
        }
    },
	'YamahaRegistration': {
        'NAME': 'YamahaRegistration',
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '192.168.100.61',
        'USER': 'sa',
        'PASSWORD': 'dataport',
        'OPTIONS': {
            'driver' : 'SQL Server Native Client 11.0',
            'driver_supports_utf8' : 'True',
            'use_legacy_date_fields': 'True'
        }
    },
    'SDMSMirror': {
        'NAME': 'SDMSMirror',
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '192.168.100.20',
        'USER': 'sa',
        'PASSWORD': 'dataport',
        'OPTIONS': {
            'driver' : 'SQL Server Native Client 11.0',
            'driver_supports_utf8' : 'True',
            'use_legacy_date_fields': 'True'
        }
    },
	'YamahaBooking': {
       'NAME': 'yamahan',
       'ENGINE': 'sql_server.pyodbc',
       'HOST': '192.168.100.61',
       'USER': 'sa',
       'PASSWORD': 'dataport',
       'OPTIONS': {
           'driver' : 'SQL Server Native Client 11.0',
           'driver_supports_utf8' : 'True',
           'use_legacy_date_fields': 'True',
           'autocommit': True,
       }
    },
	'LocationTracker': {
       'NAME': 'LocationTracker',
       'ENGINE': 'sql_server.pyodbc',
       'HOST': '192.168.100.62',
       'USER': 'sa',
       'PASSWORD': 'dataport',
       'OPTIONS': {
           'driver' : 'SQL Server Native Client 11.0',
           'driver_supports_utf8' : 'True',
           'use_legacy_date_fields': 'True',
           'autocommit': True,
       }
    },
    'ServiceTrack': {
        'NAME': 'ServiceTrack',
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '192.168.100.62',
        'USER': 'sa',
        'PASSWORD': 'dataport',
        'OPTIONS': {
            'driver' : 'SQL Server Native Client 11.0',
            'driver_supports_utf8' : 'True',
            'use_legacy_date_fields': 'True'
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#REST_FRAMEWORK = {
#    'DEFAULT_AUTHENTICATION_CLASSES': (
#        'rest_framework.authentication.TokenAuthentication',
#    ),
#    'DEFAULT_PERMISSION_CLASSES': (
#        'rest_framework.permissions.IsAuthenticated', )
#}

#MIDDLEWARE_CLASSES = (
#    'YamahaBookingApp.CorsMiddleware' 
#)

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

#CORS_ORIGIN_ALLOW_ALL = True



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

#USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
#FILE_UPLOAD_PERMISSIONS = 0o644
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

MEDIA_URL = 'PaySlip/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'PaySlip')
