# Generated by Django 2.1.1 on 2018-11-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='CustomerId', primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(db_column='CompanyName', max_length=255)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'managed': False,
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='ForwardToEEorSPE',
            fields=[
                ('id', models.AutoField(db_column='ApprovedByEEorSPEId', primary_key=True, serialize=False)),
                ('ApprovedDate', models.DateTimeField(auto_now_add=True, db_column='ApprovedDate')),
                ('Status', models.CharField(db_column='Status', max_length=10)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'managed': False,
                'db_table': 'ForwardToEEorSPE',
            },
        ),
        migrations.CreateModel(
            name='ForwardToSEorSSPE',
            fields=[
                ('id', models.AutoField(db_column='ApprovedBySSEOrSSPId', primary_key=True, serialize=False)),
                ('ApprovedDate', models.DateTimeField(auto_now_add=True, db_column='ApprovedDate')),
                ('Status', models.CharField(db_column='Status', max_length=10)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
                ('IsForwarded', models.CharField(db_column='IsForwarded', max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'ForwardToSEorSSPE',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('RoleName', models.CharField(db_column='RoleName', max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(db_column='ServiceId', primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(db_column='CompanyName', max_length=255)),
                ('ContactPerson', models.CharField(db_column='ContactPerson', max_length=255)),
                ('ContactPersonType', models.CharField(db_column='ContactPersonType', max_length=255)),
                ('ServiceTime', models.DateTimeField(db_column='ServiceTime')),
                ('Model', models.CharField(db_column='Model', max_length=255)),
                ('Chassis', models.CharField(db_column='Chassis', max_length=255)),
                ('HRM', models.CharField(db_column='HRM', max_length=255)),
                ('ServiceType', models.CharField(db_column='ServiceType', max_length=255)),
                ('Remark', models.CharField(db_column='Remark', max_length=255)),
                ('Latitude', models.CharField(db_column='Latitude', max_length=255)),
                ('Longitude', models.CharField(db_column='Longitude', max_length=255)),
                ('Status', models.CharField(db_column='Status', max_length=20)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'managed': False,
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('UserId', models.CharField(db_column='UserId', max_length=50)),
                ('UserName', models.CharField(db_column='UserName', max_length=255)),
                ('Password', models.CharField(db_column='Password', max_length=100)),
                ('StaffId', models.CharField(db_column='StaffId', max_length=100)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'managed': False,
                'db_table': 'UserManager',
            },
        ),
    ]
